### ISSUE TITLE
(feat) update table/endpts - see description for details

### ISSUE THREAD

**Issue by sunniemao** [nano-ngage/ngage-db#12]
-add endpt to return boolean (true) if user's last presentation has 0 questions OR last pid for user
-add title to presentation table
-add put req for presentation table
-add delete to presentation table
-add put for question table
-add delete for question table
-return answer ids on post
-add put for answer table
-add delete for answer table

**Comment by shpatenrick** [comment]
finished answer endpoints

**Comment by shpatenrick** [comment]
finish questions

**Comment by shpatenrick** [comment]
DONE
